📄 Documentation:
  - any: [ 'README.md', '*/README.md' ]

⚙️ Config:
  - '.github/*'
  - '.github/**/*'
  - 'dangerfile.js'
  - '.gitignore'
  - 'tsconfig.json'
  - '.prettierignore'
  - '.prettierrc'
  - '.eslintignore'
  - '.eslintrc.js'
  - 'Dockerfile'
  - 'dockerignore'
  - 'Dockerfile.dockerignore'
  - 'Jenkinsfile'

📦 Dependencies:
  - 'package.json'
  - 'yarn.lock'
  - 'package-lock.json'
  - 'apps/**/package.json'
  - 'apps/**/yarn.lock'
  - 'apps/**/package-lock.json'

🏗️ Env:
  - 'apps/**/.env.*'

🧱 DTO:
  - '**/*.dto.ts'
  - '**/*Dto.ts'
  - '**/*DTO.ts'

🧪 Tests:
  - apps/**/*.spec.*

🔒 Safe Service:
  - apps/safe_service_proxy/*
  - apps/safe_service_proxy/**/*

🔄 Swap Service:
  - apps/swap*/*
  - apps/swap*/**/*

🎌 Integration Service:
  - apps/integration_service/*
  - apps/integration_service/**/*

🚪 Gateway Service:
  - apps/gateway_service/*
  - apps/gateway_service/**/*

👤 Account Service:
  - apps/account_service/*
  - apps/account_service/**/*

🏷️ Price Service:
  - apps/price_service/*
  - apps/price_service/**/*

📚 Common Libraries:
  - libraries/common/*
  - libraries/common/**/*

👷 Job:
  - jobs/*
  - jobs/**/*

👷️ Lambda:
  - lambda/src/*
  - lambda/src/**/*
  - apps/lambda_prices/*
  - apps/lambda_prices/**/*
