📄 Documentation:
  - any: [ 'README.md', '*/README.md' ]

⚙️ Config:
  - any: [
      '.github/*',
      'dangerfile.js',
      '.gitignore',
      'tsconfig.json',
      '.prettierignore',
      '.prettierrc',
      '.eslintignore',
      '.eslintrc.js',
      'Dockerfile',
      'dockerignore',
      'Dockerfile.dockerignore',
      'Jenkinsfile'
  ]

📦 Dependencies:
  - any: [ 'package.json', 'yarn.lock', 'package-lock.json', '**/package.json', '**/yarn.lock', '**/package-lock.json' ]

🏗️ Env:
  - '**/.env.*'

DTO:
  - any: [ '**/*.dto.ts', '**/*Dto.ts', '**/*DTO.ts' ]

🧪 Tests:
  - apps/**/*.spec.*

👷 Job:
  - any:
      [
          'price_service_crawlers/*',
          'integration_service_crawlers/*',
          'account_service_consumers/*',
          '*/account_service_crawlers',
          '*crawlers/*',
          '*consumers/*'
      ]

🔒 Safe Service:
  - apps/safe_service_proxy/*

🔄 Swap Service:
  - apps/swap*/*

🎌 Integration Service:
  - apps/integration_service/*

🚪 Gateway Service:
  - apps/api_gateway/*

👤 Account Service:
  - apps/account_service/*

🏷️ Price Service:
  - apps/price_service/*

👷️ Lambda:
  - any: [ 'lambda/src/*', 'apps/lambda_prices/*']
