configMaps:
  amm:
    AMM_SUSHISWAP_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/tretiakpk/sushiswap-fork-of-uniswap-v2
    AMM_UNISWAP_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v2
    AMM_BALANCER_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/dashvm7/balancer
    AAVEGOTCHI_SUBGRAPH_ETHEREUM: https://api.thegraph.com/subgraphs/name/aavegotchi/aavegotchi-ethereum
    AAVEGOTCHI_SUBGRAPH_POLYGON: https://api.thegraph.com/subgraphs/name/aavegotchi/aavegotchi-core-matic
    AAVEGOTCHI_SUBGRAPH_SVG: https://api.thegraph.com/subgraphs/name/froid1911/aavegotchi-svg
  blocks:
    BLOCKS_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/blocklytics/ethereum-blocks
  links:
    ETHEREUM_URL: https://eth-trace.gateway.pokt.network/v1/lb/619fad2eb2d0dd003950f26b
    ETH_URL: https://eth-trace.gateway.pokt.network/v1/lb/619fad2eb2d0dd003950f26b
    BINANCE_URL: https://bsc--mainnet--rpc.datahub.figment.io/apikey/91e126bee34f826357715bff8eac3441
    BSC_URL: https://bsc--mainnet--rpc.datahub.figment.io/apikey/91e126bee34f826357715bff8eac3441
    POLYGON_URL: https://speedy-nodes-nyc.moralis.io/173c906bbd79b4c01dc6034b/polygon/mainnet/archive
    FANTOM_URL: https://rpc.ftm.tools/
    FTM_URL: https://rpc.ftm.tools/
    AVALANCHE_URL: https://avalanche--mainnet--rpc.datahub.figment.io/apikey/eb4092c651b0af2e17fd2ecb0f5966bd/ext/bc/C/rpc
    AVAX_URL: https://avalanche--mainnet--rpc.datahub.figment.io/apikey/eb4092c651b0af2e17fd2ecb0f5966bd/ext/bc/C/rpc
    ARBITRUM_URL: https://rpc.ankr.com/arbitrum
    XDAI_URL: https://xdai-archive.blockscout.com
    CELO_URL: https://celo-mainnet--rpc.datahub.figment.io/apikey/4db2dc6e107f70e18fd4bdbb549b9aa1/
    MOONRIVER_URL: https://rpc.api.moonriver.moonbeam.network
    MRIVER_URL: https://rpc.api.moonriver.moonbeam.network
    HARMONY_URL: https://a.api.s0.t.hmny.io
    HARM_URL: https://a.api.s0.t.hmny.io
    HECO_URL: https://http-mainnet.hecochain.com/
    POLYGON_RPC_URL: https://polygon-rpc.com/
    SOLANA_URL: https://rpc.ankr.com/solana
    SOL_URL: https://solana-api.projectserum.com/
    OKEX_URL: https://exchainrpc.okex.org
    CRONOS_URL: https://evm-cronos.crypto.org
    BOBA_URL: https://mainnet.boba.network/
    KUCOIN_URL: https://rpc-mainnet.kcc.network
    OPTIMISM_URL: https://mainnet.optimism.io/
    OPT_URL: https://mainnet.optimism.io/
    AURORA_URL: https://mainnet.aurora.dev
    TERRA_URL: https://lcd.terra.dev
    METIS_URL: https://andromeda-rpc.metis.io/
    RONIN_URL: https://api.roninchain.com/rpc
    GNOSIS_URL: https://poa-xdai-archival.gateway.pokt.network/v1/lb/61f959410d66d80038fc1da0
    KLAYTN_URL: https://public-node-api.klaytnapi.com/v1/cypress
    FUSE_URL: https://rpc.fuse.io
    KAVA_URL: https://rpc.kava.io
    CARDANO_URL: https://cardano-mainnet.blockfrost.io
    COSMOS_URL: https://cosmoshub-4--rpc--archive.datahub.figment.io/apikey/91e126bee34f826357715bff8eac3441/
    OSMOSIS_URL: https://osmosis-1--rpc--archive.datahub.figment.io/apikey/91e126bee34f826357715bff8eac3441/
    SECRET_URL: https://secret-3--rpc--archive.datahub.figment.io/apikey/91e126bee34f826357715bff8eac3441/
    NEAR_URL: https://mainnet.aurora.dev/
  endpoints:
    PRICE_SERVICE_HOST: http://price
    PRICE_SERVICE_PORT: 80
    PRICES_PATH: v1/prices
    PRICE_SERVICE_MAIN_COIN_ADDRESS: 0x0000000000000000000000000000000000000000
    KAVA_LCD: https://api2.kava.io
    OSMOSIS_LCD: https://lcd.osmosis.zone
    COSMOS_LCD: https://lcd-cosmos.cosmostation.io
    SECRET_LCD: https://lcd-secret.cosmostation.io
  contracts:
    ETH_BALANCES_CHECKER_ADDRESS: '0x1861eb1cc764032509e4d2ff545138be0ad3b240'
    BSC_BALANCES_CHECKER_ADDRESS: '0x1861eb1cc764032509e4d2ff545138be0ad3b240'
    POLYGON_BALANCES_CHECKER_ADDRESS: '0x1502c3c8e63873b1b162ed27a218069dc1486f51'
    FTM_BALANCES_CHECKER_ADDRESS: '0x1861eb1Cc764032509e4d2FF545138Be0ad3B240'
    AVAX_BALANCES_CHECKER_ADDRESS: '0x1861eb1Cc764032509e4d2FF545138Be0ad3B240'
    ARBITRUM_BALANCES_CHECKER_ADDRESS: '0x1861eb1cc764032509e4d2ff545138be0ad3b240'
    XDAI_BALANCES_CHECKER_ADDRESS: '0x1861eb1cc764032509e4d2ff545138be0ad3b240'
    HARMONY_BALANCES_CHECKER_ADDRESS: '0x1861eb1cc764032509e4d2ff545138be0ad3b240'
    CELO_BALANCES_CHECKER_ADDRESS: '0x1861eb1cc764032509e4d2ff545138be0ad3b240'
    MOONRIVER_BALANCES_CHECKER_ADDRESS: '0x1861eb1cc764032509e4d2ff545138be0ad3b240'
    HECO_BALANCES_CHECKER_ADDRESS: '0x1861eb1cc764032509e4d2ff545138be0ad3b240'
    OKEX_BALANCES_CHECKER_ADDRESS: '0x1861eb1cc764032509e4d2ff545138be0ad3b240'
    CRONOS_BALANCES_CHECKER_ADDRESS: '0xE5B89aA6fb36E31BeA8AB13B73eB3291De95D4E7'
    KCC_BALANCES_CHECKER_ADDRESS: '0x11e14AEABbCD1774B37C4EE5E1aD3c831ACc2A2c'
    NEAR_BALANCES_CHECKER_ADDRESS: '0x1861eb1Cc764032509e4d2FF545138Be0ad3B240'
    METIS_BALANCES_CHECKER_ADDRESS: '0x1861eb1cc764032509e4d2ff545138be0ad3b240'
  delegations:
    TERRA_DELEGATION_API_URL: https://lcd.terra.dev
    SOLANA_DELEGATION_API_URL: https://api.solanabeach.io
    CARDANO_DELEGATION_API_URL: https://cardano-mainnet.blockfrost.io
  logs:
    LOG_AWS_ENABLED: true
    LOG_LEVEL: debug
    NODE_ENV: production
  params:
    ETH_BALANCES_CHECKER_BATCH_SIZE: 2000
    AWS_XRAY_DAEMON_ADDRESS: xray-service.default:2000

secrets:
- database
- redis
- bscscan
- etherscan
- logs
- covalent
- polygonscan
- sentry
- cardano
- opensea
