FROM amazon/aws-lambda-nodejs:14
ADD ./apps ./apps
ADD ./jobs ./jobs
ADD ./libs ./libs
ADD ./nest-cli.json ./
ADD ./package.json ./
ADD ./tsconfig.json ./
ADD ./tsconfig.build.json ./
RUN yum install git -y
RUN npm install --global yarn
RUN yarn install
#ARG function_name
#ENV env_function_name=$function_name
RUN yarn run lambda_vault-build
#ENTRYPOINT [ "node" ]
CMD [ "dist/jobs/lambda_vaults/src/main.bootstrap" ]
