FROM node:14.17 as development

# Install development dependencies
WORKDIR /usr/src/app
COPY package*.json ./
COPY yarn.lock ./
RUN yarn install --loglevel verbose

# Build application
COPY . .
RUN yarn account-build

# Configure application startup command
CMD ["npm", "run", "start"]



FROM node:14.17 as pre-production
# Install runtime dependencies
WORKDIR /usr/src/app
COPY package*.json ./
COPY yarn.lock ./
RUN yarn install --only=production

FROM node:14.17-alpine as production

# Setup default environment variables
ENV NODE_ENV production
# Copy runtime dependencies and application code
WORKDIR /usr/src/app
COPY --from=pre-production /usr/src/app/node_modules ./node_modules
COPY --from=development /usr/src/app/dist ./dist
#COPY --from=development /usr/src/app/apps/account/config/.env /dist/apps/account/.env
RUN touch /usr/src/app/dist/apps/account/.env

# Configure application startup command
ENTRYPOINT ["node"]
CMD ["dist/apps/account/src/main"]
