version: "3"

services:

  account_service:

    build: account_service/

    ports:
    - "3001:3000"

  api_gateway:

    build: api_gateway/

    ports:
    - "3000:3000"

    depends_on:
      - account_service
