version: '3'

services:

  pancake_service:
    build: pancake_service/

    ports:
      - '3005:3005'

  price_service:
    build: price_service/

    ports:
      - '3004:3004'

  integration_service:
    build: integration_service/

    ports:
      - '3003:3003'

    depends_on:
      - price_service

  swap_service:
    build: swap_service/

    ports:
      - '3002:3002'

  account_service:
    build: account_service/

    ports:
      - '3001:3001'

  api_gateway:
    build: api_gateway/

    ports:
      - '3000:3000'

    depends_on:
      - pancake_service
      - price_service
      - integration_service
      - swap_service
      - account_service
