FROM node:14.17 as development

#Uncomment for MacOS M1
#ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true

# Install development dependencies
WORKDIR /usr/src/app
COPY package*.json ./
COPY yarn.lock ./

RUN yarn install --loglevel verbose

# Additional packages for Docker
# needed to be modified depending on the target platform - where the mage is going to be run
# x64 (regular Intel) , arm64v8 (MacOS M1)
RUN SHARP_IGNORE_GLOBAL_LIBVIPS=1 npm_config_arch=x64 npm_config_platform=linuxmusl yarn add sharp
#RUN SHARP_IGNORE_GLOBAL_LIBVIPS=1 npm_config_arch=arm64v8 npm_config_platform=linuxmusl yarn add sharp

# Build application
COPY . .
RUN yarn assets-build

# Configure application startup command
CMD ["npm", "run", "start"]

FROM node:14.17 as pre-production

#Uncomment for MacOS M1
#ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true

# Install runtime dependencies
WORKDIR /usr/src/app
COPY package*.json ./
COPY yarn.lock ./

RUN yarn install --only=production

# Additional packages for Docker
# needed to be modified depending on the target platform - where the mage is going to be run
# x64 (regular Intel) , arm64v8 (MacOS M1)
RUN SHARP_IGNORE_GLOBAL_LIBVIPS=1 npm_config_arch=x64 npm_config_platform=linuxmusl yarn add sharp
#RUN SHARP_IGNORE_GLOBAL_LIBVIPS=1 npm_config_arch=arm64v8 npm_config_platform=linuxmusl yarn add sharp

FROM node:14.17-alpine as production

# Setup default environment variables
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true
ENV NODE_ENV production
# Copy runtime dependencies and application code
WORKDIR /usr/src/app

COPY --from=pre-production /usr/src/app/node_modules ./node_modules
COPY --from=development /usr/src/app/dist ./dist
#COPY --from=development /usr/src/app/apps/assets_service/config/.env /dist/apps/assets_service/.env

RUN touch /usr/src/app/dist/apps/assets_service/.env

# Configure application startup command
ENTRYPOINT ["node"]
CMD ["dist/apps/assets_service/src/main"]
