FROM node:14.17 as development

# Install development dependencies
WORKDIR /usr/src/app
COPY package*.json ./
RUN yarn install --loglevel verbose

# Build application
COPY . .
RUN ls -l apps
RUN yarn price-build

# Configure application startup command
CMD ["npm", "run", "start"]



FROM node:14.17 as pre-production
# Install runtime dependencies
WORKDIR /usr/src/app
COPY package*.json ./
RUN yarn install --only=production

FROM node:14.17-alpine as production

# Setup default environment variables
ENV NODE_ENV production
# Copy runtime dependencies and application code
WORKDIR /usr/src/app
COPY --from=pre-production /usr/src/app/node_modules ./node_modules
#COPY --from=development /usr/src/app/apps/price_service/config/.env /dist/apps/price_service/.env
COPY --from=development /usr/src/app/apps/price_service/config/values.yaml /dist/apps/price_service/values.yaml
COPY --from=development /usr/src/app/dist ./dist
RUN touch /dist/apps/price_service/.env

# Configure application startup command
ENTRYPOINT ["node"]
CMD ["dist/apps/price_service/src/main"]
