ingress:
  enabled: true
  host: gateway.staging.defyield.xyz

configMaps:
  common:
    PRICE_SERVICE_MAIN_COIN_ADDRESS: "0x0000000000000000000000000000000000000000"
    MAIL_HIRE_FROM: mail@defiyield.app
    MAIL_HIRE_TO: hr@defiyield.app
    MAIL_QUESTION_FROM: mail@defiyield.app
    MAIL_QUESTION_TO: hr@defiyield.app
  gas:
    GAS_API_URL: https://data-api.defipulse.com/api/v1
    GAS_CURRENT_PATH: egs/api/ethgasAPI.json
    GAS_API_KEY: 7a54010743b9e2692bd52232e3e06c871df2261205dcb0663a57235b2306
    GAS_HISTORY_PATH: gas-hist
  portal:
    DEFIYIELD_INFO_2_URL: https://api2.defiyield.info
    DEFIYIELD_INFO_MAIN_URL: https://apimain.defiyield.info
    ETH_URL: https://eth-trace.gateway.pokt.network/v1/lb/619fad2eb2d0dd003950f26b
    SOLANA_NAME_SERVICE_PUBLIC_KEY: 58PwtjSDuFHuUkYjH9BYnnQKHfwo9reZhC2zMJv9JPkx
    SOL_URL: https://solana-api.projectserum.com
  endpoints:
    PRICE_SERVICE_HOST: http://price-service
    PRICE_SERVICE_PORT: 80
    PRICES_PATH: v1/prices
    INTEGRATION_SERVICE_HOST: http://integration-service
    INTEGRATION_SERVICE_PORT: 80
    INTEGRATION_SEARCH_URL: v1/protocols/search
    ACCOUNT_SERVICE_HOST: http://account-service
    ACCOUNT_SERVICE_PORT: 80
    POOLS_SERVICE_URL: https://integration-service
    VAULTS_SERVICE_URL: https://integration-service
    IL_CALCULATOR: https://ilapi1.defiyield.info/api/v2/calc
    SAFE_PROXY_SERVICE_HOST: http://safe.proxy.dfyield.xyz
    SAFE_PROXY_SERVICE_PORT: 80
    OPPORTUNITIES_SERVICE_HOST: https://eop.dfyield.xyz
    OPPORTUNITIES_SERVICE_PORT: 443
  logs:
    LOG_AWS_ENABLED: true
    LOG_LEVEL: debug
    NODE_ENV: production
    SENTRY_DSN: https://d3623ec62dd14dbe81d0b82391c95d5d@o1128743.ingest.sentry.io/6171835

secrets:
- mailer
- redis
- bscscan
- etherscan
- logs
