configMaps:
  amm:
    AMM_SUSHISWAP_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/tretiakpk/sushiswap-fork-of-uniswap-v2
    AMM_UNISWAP_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v2
    AMM_BALANCER_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/dashvm7/balancer
  blocks:
    BLOCKS_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/blocklytics/ethereum-blocks
  links:
    ETH_URL: https://mainnet.infura.io/v3/d38bddd842b94305a23f91596991a9eb
    BSC_URL: https://bsc-dataseed.binance.org
    POLYGON_URL: https://rpc-mainnet.matic.network/
    FTM_URL: https://rpc.ftm.tools/
    POLYGONSCAN_URL: https://api.polygonscan.com/api
    POLYGONSCAN_KEY: TXKCKK5YXGBWEH8YTGWNKCSJPGFKQ2IZZF
  endpoints:
    PRICE_SERVICE_HOST: http://price-service
    PRICE_SERVICE_PORT: 80
    PRICES_PATH: v1/prices
    PRICE_SERVICE_MAIN_COIN_ADDRESS: 0x0000000000000000000000000000000000000000
    COVALENT_URL: https://api.covalenthq.com/v1
    COVALENT_KEY: ckey_8a12ec5b8243410b9960bb90ad0
    POLYGON_URL: https://api.polygonscan.com/api
    POLYGON_KEY: TXKCKK5YXGBWEH8YTGWNKCSJPGFKQ2IZZF

secrets:
- database
- redis
- bscscan
- etherscan
