configMaps:
  amm:
    AMM_SUSHISWAP_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/tretiakpk/sushiswap-fork-of-uniswap-v2
    AMM_UNISWAP_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v2
    AMM_BALANCER_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/dashvm7/balancer
  blocks:
    BLOCKS_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/blocklytics/ethereum-blocks
  links:
    ETH_URL: https://mainnet.infura.io/v3/d38bddd842b94305a23f91596991a9eb
    BSC_URL: https://bsc-dataseed.binance.org
  endpoints:
    PRICE_SERVICE_HOST: http://price-service
    PRICE_SERVICE_PORT: 80
    PRICES_PATH: v1/prices
    PRICE_SERVICE_MAIN_COIN_ADDRESS: 0x0000000000000000000000000000000000000000

secrets:
- database
- redis
- bscscan
- etherscan