export default `[
  {
     "anonymous":false,
     "inputs":[
        {
           "indexed":true,
           "internalType":"address",
           "name":"previousOwner",
           "type":"address"
        },
        {
           "indexed":true,
           "internalType":"address",
           "name":"newOwner",
           "type":"address"
        }
     ],
     "name":"OwnershipTransferred",
     "type":"event"
  },
  {
     "inputs":[
        {
           "internalType":"address[]",
           "name":"tokens",
           "type":"address[]"
        },
        {
           "internalType":"uint256[]",
           "name":"exactAmountsIn",
           "type":"uint256[]"
        },
        {
           "internalType":"address",
           "name":"portfolio",
           "type":"address"
        }
     ],
     "name":"estimateDeposit",
     "outputs":[
        {
           "internalType":"uint256",
           "name":"totalLiquidityOut",
           "type":"uint256"
        }
     ],
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"address[]",
           "name":"tokens",
           "type":"address[]"
        },
        {
           "internalType":"uint256[]",
           "name":"LPTamounts",
           "type":"uint256[]"
        },
        {
           "internalType":"address",
           "name":"portfolio",
           "type":"address"
        }
     ],
     "name":"estimateWithdraw",
     "outputs":[
        {
           "internalType":"uint256[]",
           "name":"amounts",
           "type":"uint256[]"
        }
     ],
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "inputs":[
        
     ],
     "name":"getManualYieldPoolTotalStaked",
     "outputs":[
        {
           "internalType":"uint256",
           "name":"",
           "type":"uint256"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"address[][]",
           "name":"pairs",
           "type":"address[][]"
        }
     ],
     "name":"getPairContracts",
     "outputs":[
        {
           "internalType":"address[]",
           "name":"",
           "type":"address[]"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        
     ],
     "name":"getPortfolios",
     "outputs":[
        {
           "components":[
              {
                 "internalType":"string",
                 "name":"name",
                 "type":"string"
              },
              {
                 "internalType":"address",
                 "name":"contractAddress",
                 "type":"address"
              },
              {
                 "internalType":"address",
                 "name":"baseTokenAddress",
                 "type":"address"
              },
              {
                 "internalType":"address",
                 "name":"lpTokenAddress",
                 "type":"address"
              },
              {
                 "internalType":"uint256",
                 "name":"lpTokenPrice",
                 "type":"uint256"
              },
              {
                 "internalType":"uint256",
                 "name":"totalValue",
                 "type":"uint256"
              },
              {
                 "internalType":"uint256",
                 "name":"tokenCount",
                 "type":"uint256"
              },
              {
                 "components":[
                    {
                       "internalType":"address",
                       "name":"tokenAddress",
                       "type":"address"
                    },
                    {
                       "internalType":"uint256",
                       "name":"amount",
                       "type":"uint256"
                    },
                    {
                       "internalType":"uint256",
                       "name":"price",
                       "type":"uint256"
                    },
                    {
                       "internalType":"uint256",
                       "name":"depositLimit",
                       "type":"uint256"
                    },
                    {
                       "internalType":"uint256",
                       "name":"withdrawLimit",
                       "type":"uint256"
                    },
                    {
                       "internalType":"uint256",
                       "name":"depositEMAPrice",
                       "type":"uint256"
                    },
                    {
                       "internalType":"uint256",
                       "name":"withdrawEMAPrice",
                       "type":"uint256"
                    },
                    {
                       "internalType":"uint256",
                       "name":"portfolioShare",
                       "type":"uint256"
                    },
                    {
                       "internalType":"uint256",
                       "name":"targetWeight",
                       "type":"uint256"
                    }
                 ],
                 "internalType":"struct BlueshiftPortfolioAndPairRegistry.TokenInfo[]",
                 "name":"tokens",
                 "type":"tuple[]"
              }
           ],
           "internalType":"struct BlueshiftPortfolioAndPairRegistry.PortfolioInfo[]",
           "name":"",
           "type":"tuple[]"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        
     ],
     "name":"governance",
     "outputs":[
        {
           "internalType":"address",
           "name":"",
           "type":"address"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"address",
           "name":"_governance",
           "type":"address"
        },
        {
           "internalType":"address",
           "name":"_poolFactory",
           "type":"address"
        },
        {
           "internalType":"address",
           "name":"_manualPool",
           "type":"address"
        },
        {
           "internalType":"address",
           "name":"_autoPool",
           "type":"address"
        }
     ],
     "name":"initialize",
     "outputs":[
        
     ],
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "inputs":[
        
     ],
     "name":"owner",
     "outputs":[
        {
           "internalType":"address",
           "name":"",
           "type":"address"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"string",
           "name":"name",
           "type":"string"
        },
        {
           "internalType":"address",
           "name":"contractAddress",
           "type":"address"
        }
     ],
     "name":"registerPortfolio",
     "outputs":[
        
     ],
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"uint256",
           "name":"",
           "type":"uint256"
        }
     ],
     "name":"registeredPortfolios",
     "outputs":[
        {
           "internalType":"string",
           "name":"name",
           "type":"string"
        },
        {
           "internalType":"address",
           "name":"contractAddress",
           "type":"address"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        
     ],
     "name":"renounceOwnership",
     "outputs":[
        
     ],
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"address",
           "name":"newOwner",
           "type":"address"
        }
     ],
     "name":"transferOwnership",
     "outputs":[
        
     ],
     "stateMutability":"nonpayable",
     "type":"function"
  }
]`;
