ingress:
  enabled: true
  host: devassets.defiyield.app

configMaps:
  rpc:
    ETH_URL: https://eth-trace.gateway.pokt.network/v1/lb/619fad2eb2d0dd003950f26b
    SOL_URL: http://api.mainnet-beta.solana.com
    TERRA_URL: https://lcd.terra.dev
  services:
    ACCOUNT_SERVICE_CHAINS_LIST_URL: https://acc.dfyield.xyz/v1/chains
  logs:
    LOG_AWS_ENABLED: true
    LOG_LEVEL: debug
    NODE_ENV: development
    AWS_XRAY_DAEMON_ADDRESS: xray-service.default:2000

secrets:
  - database-assets
  - redis
  - logs
  - cardano
  - debank
  - tokenlist