FROM amazon/aws-lambda-nodejs:14
ADD ./jobs/lambda_scheduler ./
RUN npm install --global yarn
RUN yarn install
#ARG function_name
#ENV env_function_name=$function_name
RUN yarn run compile --outDir ./
#ENTRYPOINT [ "node" ]
CMD [ "app.lambdaHandler" ]
