FROM node:14.17 as development

# Install development dependencies
WORKDIR /usr/src/app
COPY package*.json ./
COPY yarn.lock ./
RUN yarn install --loglevel verbose

# Build application
COPY . .
RUN yarn categorization_tool-build
#RUN yarn categorization_tool-migration:generate
# RUN npm run categorization_tool-migration:generate -- -n first

# Configure application startup command
CMD ["npm", "run", "start"]


FROM node:14.17 as pre-production
# Install runtime dependencies
WORKDIR /usr/src/app
COPY package*.json ./
COPY yarn.lock ./
RUN yarn install --only=production

FROM node:14.17-slim as production

# Setup default environment variables
ENV NODE_ENV production
# Copy runtime dependencies and application code
WORKDIR /usr/src/app
# Install latest chrome dev package and fonts to support major charsets (Chinese, Japanese, Arabic, Hebrew, Thai and a few others)
# Note: this installs the necessary libs to make the bundled version of Chromium that Puppeteer
# installs, work.
RUN apt update \
    && apt install -y wget gnupg \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt update \
    && apt install -y google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 \
      --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*
COPY --from=pre-production /usr/src/app/node_modules ./node_modules
COPY --from=development /usr/src/app/dist ./dist
#COPY --from=development /usr/src/app/apps/categorization_tool/ormconfig.ts ./dist/apps/categorization_tool/ormconfig.ts
#COPY --from=development /usr/src/app/ormconfig.ts ./
#COPY --from=development /usr/src/app/apps/categorization_tool/config/.env /dist/apps/categorization_tool/.env
RUN touch /usr/src/app/dist/apps/categorization_tool/.env

# Configure application startup command
ENTRYPOINT ["node"]
CMD ["dist/apps/categorization_tool/src/main"]
