application:
  name: ""
  version: ""
  environment: ""
  maxVersions: 5
  log_level: debug

replicas: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 4
        periodSeconds: 15
      selectPolicy: Max

service:
  host: "0.0.0.0"
  port: 3000

imageOverride: ""
image:
  registry: 625623467395.dkr.ecr.eu-central-1.amazonaws.com
  pullPolicy: IfNotPresent

readinessProbe:
  httpGet:
    port: http
    path: /v1/status
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 3
  successThreshold: 1
  failureThreshold: 5

resources:
  requests:
    cpu: 100m
    memory: 200Mi
  limits:
    cpu: 200m
    memory: 600Mi

serviceAccount:
  create: true
  iam_role_arn: arn:aws:iam::625623467395:role/AWSSecretsStoreCSIDriverIAMRole

securityContext:
  runAsUser: 0
  fsGroup: 65534

extraContainers: |

podDisruptionBudget:
#  minAvailable: 1
  maxUnavailable: 1

ingress:
  annotations: {}
  certificate_arn: arn:aws:acm:eu-central-1:625623467395:certificate/0451fee0-71c4-4989-b584-189e73945b0b
  wafv2_acl_arn: arn:aws:wafv2:eu-central-1:625623467395:regional/webacl/defiyield-backend-production/9eadcd76-96cb-4761-aaf4-5b4320f4d249
  certificate_arn_stg: arn:aws:acm:us-west-2:625623467395:certificate/a19eacc1-004c-4ce4-ab7f-fcb0f3d911b8
  wafv2_acl_arn_stg: arn:aws:wafv2:us-east-2:625623467395:regional/webacl/defiyield-backend-staging/71e7a1f4-1edb-404b-9440-c03a64fffcb5

configMaps:
  common:
    LOG_ERROR_FILE: error.log
    LOG_COMBINED_FILE: combined.log
  db:
    DB_CONNECTION: postgres
    DB_SYNCHRONIZE: false
    DB_LOGGING: true

configMapsAWS:

secrets:
  - database

initContainer:
  enabled: false
  name: init
  image: ""
  spec:
    command: [ "sh", "-c" ]

