application:
  name: ""
  version: ""
  environment: ""
  maxVersions: 5

replicas: 1

service:
  host: "0.0.0.0"
  port: 3000

imageOverride: ""
image:
  registry: 625623467395.dkr.ecr.eu-central-1.amazonaws.com
  pullPolicy: IfNotPresent

readinessProbe:
  httpGet:
    port: http
    path: /v1/status
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 3
  successThreshold: 1
  failureThreshold: 5

resources:
  requests:
    cpu: 200m
    memory: 400Mi
  limits:
    cpu: "2"
    memory: 2Gi

ingress:
  enabled: false
  host: defyield.xyz
  certificate_arn: arn:aws:acm:eu-central-1:625623467395:certificate/3a16d612-0761-4f64-82f9-2f3892d2faf1
  wafv2_acl_arn: arn:aws:wafv2:eu-central-1:625623467395:regional/webacl/defiyield-backend-production/9eadcd76-96cb-4761-aaf4-5b4320f4d249

configMaps:
  common:
    ENV: .env
    LOG_ERROR_FILE: error.log
    LOG_COMBINED_FILE: combined.log
    LOG_LEVEL: info
  db:
    DB_CONNECTION: postgres
    DB_HOST: pg-main.c2ibi3sjxz3a.eu-central-1.rds.amazonaws.com
    DB_PORT: 5432
    DB_DATABASE: defi
    DB_SYNCHRONIZE: false
    DB_LOGGING: true

secrets:
- db