configMaps:
  logs:
    LOG_AWS_ENABLED: true
    LOG_LEVEL: debug
    NODE_ENV: development

resources:
  requests:
    cpu: 50m
    memory: 100Mi
  limits:
    cpu: 100m
    memory: 100Mi

secrets:
  - redis
