configMaps:
  common:
    ETH_TOKEN_USD_PRICE_JOB_NAME: ETH_TOKEN_USD_PRICE_UPDATE
    PRICE_SERVICE_ETH_ADDRESS: "0x0000000000000000000000000000000000000000"
  endpoints:
    PRICE_SERVICE_ENDPOINT: http://price-service/v1/prices
    PRICE_SERVICE_HOST: http://price-service
    PRICE_SERVICE_PORT: 80
    PRICE_STATUS: v1/status
    PRICES_PATH: v1/prices

secrets:
- database
- mongo