ingress:
  enabled: true
  host: integration.defiyield.app

configMaps:
  amm:
    AMM_SUSHISWAP_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/tretiakpk/sushiswap-fork-of-uniswap-v2
    AMM_UNISWAP_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v2
    AMM_PANCAKE_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/tretiakpk/cake
    AMM_PANGOLIN_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/dasconnor/pangolin-dex
    AUTOFARM_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/mikephul/autofarm
    AAVE_ETH_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/aave/protocol-v2
    AAVE_PLG_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/aave/aave-v2-matic
    AMM_UNISWAP_V3_ETH_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v3
    SPOOKYSWAP_FARM_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/defilord/spookyswap-farm
    SPOOKYSWAP_ACELAB_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/defilord/spookyswap-acelab
    QUICKSWAP_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/sameepsi/quickswap05
    ALPACA_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/defilord/alpaca-fair-launch
    ALPACA_API_URL: https://api.alpacafinance.org/v1/positions
    YEARN_V1_ETH_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/iearn-finance/yearn-finance
    SUSHISWAP_ETH_EXCHANGE_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/sushiswap/exchange
    SUSHISWAP_BSC_EXCHANGE_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/sushiswap/bsc-exchange
    SUSHISWAP_OKEX_EXCHANGE_SUBGRAPH_URL: https://q.hg.network/okex-exchange/oec
    SUSHISWAP_XDAI_EXCHANGE_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/sushiswap/xdai-exchange
    SUSHISWAP_HECO_EXCHANGE_SUBGRAPH_URL: https://q.hg.network/heco-exchange/heco
    SUSHISWAP_MATIC_EXCHANGE_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/sushiswap/matic-exchange
    SUSHISWAP_FTM_EXCHANGE_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/sushiswap/fantom-exchange
    SUSHISWAP_ARBI_EXCHANGE_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/sushiswap/arbitrum-exchange
    SUSHISWAP_CELO_EXCHANGE_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/sushiswap/celo-exchange
    SUSHISWAP_AVAX_EXCHANGE_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/sushiswap/avalanche-exchange
    SUSHISWAP_ONE_EXCHANGE_SUBGRAPH_URL: https://sushi.graph.t.hmny.io/subgraphs/name/sushiswap/harmony-exchange
    SUSHISWAP_ETH_MASTERCHEF_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/sushiswap/master-chef
    SUSHISWAP_ETH_SUSHIBAR_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/sushiswap/sushi-bar
    SUSHISWAP_ETH_BENTOBOX_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/sushiswap/bentobox
    SUSHISWAP_PLG_MINICHEF_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/sushiswap/matic-minichef
    AAVE_AVAX_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/aave/protocol-v2-avalanche
    YEARN_ETH_SUBGRAPH_URL: 'https://api.thegraph.com/subgraphs/name/salazarguille/yearn-vaults-v2-subgraph-mainnet'
    YEARN_FTM_SUBGRAPH_URL: 'https://api.thegraph.com/subgraphs/name/yearn/yearn-vaults-v2-fantom'
    SUSHISWAP_ARBI_BENTOBOX_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/sushiswap/arbitrum-bentobox
    SUSHISWAP_BSC_BENTOBOX_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/sushiswap/bsc-bentobox
    SUSHISWAP_PLG_BENTOBOX_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/sushiswap/matic-bentobox
    SUSHISWAP_XDAI_BENTOBOX_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/sushiswap/xdai-bentobox
    SUSHISWAP_ARBI_MINICHEF_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/matthewlilley/arbitrum-minichef
    SUSHISWAP_CELO_MINICHEF_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/sushiswap/celo-minichef
    SUSHISWAP_MRIVER_MINICHEF_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/sushiswap/moonriver-minichef
    SUSHISWAP_ONE_MINICHEF_SUBGRAPH_URL: https://sushi.graph.t.hmny.io/subgraphs/name/sushiswap/harmony-minichef
    SUSHISWAP_XDAI_MINICHEF_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/matthewlilley/xdai-minichef
    SUSHISWAP_MRIVER_EXCHANGE_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/sushiswap/moonriver-exchange
    SUSHISWAP_ETH_MASTERCHEF_V2_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/sushiswap/master-chefv2
    COMPOUND_ETH_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/cavanmflynn/compound-v2
    AMM_UNISWAP_V3_PLG_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/ianlapham/uniswap-v3-polygon
    AMM_UNISWAP_V3_OPT_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/ianlapham/optimism-post-regenesis
    AMM_UNISWAP_V3_ARBI_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/ianlapham/arbitrum-minimal
    SUSHISWAP_GNOSIS_MINICHEF_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/matthewlilley/xdai-minichef
    SUSHISWAP_GNOSIS_BENTOBOX_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/sushiswap/xdai-bentobox
    SUSHISWAP_GNOSIS_EXCHANGE_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/sushiswap/xdai-exchange
    MINSWAP_URL: https://monorepo-mainnet-prod.minswap.org/graphql
  blocks:
    BLOCKS_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/blocklytics/ethereum-blocks
  links:
    COINGECKO_API_URL: https://api.coingecko.com/api/v3/
    THEGRAPH_SUSHISWAP_STAKING_POSITIONS: https://api.thegraph.com/subgraphs/name/sushiswap/master-chef
    ETH_URL: https://mainnet.infura.io/v3/eb49fe03a73a40dc91bf236e3a604fe7
    BSC_URL: https://bsc-dataseed.binance.org
    POLYGON_RPC_URL: https://polygon-rpc.com/
    FTM_RPC_URL: https://rpc.ftm.tools
    FTM_URL: https://rpc.ftm.tools
    AUTOFARM_API_URL: https://static.autofarm.network/bsc/farm_data.json
    PANCAKEV2_MAIN_STAKING_SUBGRAPH_URL: https://api.thegraph.com/subgraphs/name/defilord/pcv2-msc
    OPEN_SEA_URL: https://api.opensea.io/api/v1
    AVAX_URL: https://api.avax.network/ext/bc/C/rpc
    CELO_URL: https://forno.celo.org
    HARM_URL: https://a.api.s0.t.hmny.io
    HECO_URL: https://http-mainnet-node.huobichain.com
    MRIVER_URL: https://rpc.moonriver.moonbeam.network
    XDAI_URL: https://rpc.xdaichain.com
    POLYGON_URL: https://polygon-rpc.com/
    SOL_URL: https://solana-api.projectserum.com/
    BOBA_URL: https://lightning-replica.boba.network
    CRONOS_URL: https://evm-cronos.crypto.org
    KCC_URL: https://rpc-mainnet.kcc.network
    OKEX_URL: https://exchainrpc.okex.org/
    OPT_URL: https://mainnet.optimism.io/
    ARBITRUM_URL: https://rpc.ankr.com/arbitrum
    SUNDAESWAP_URL: https://stats.sundaeswap.finance/graphql
    TERRA_URL: https://lcd.terra.dev
    GNOSIS_URL: https://rpc.xdaichain.com
    AURORA_URL: https://mainnet.aurora.dev
  endpoints:
    ACCOUNT_SERVICE_URL: http://account-service
    PRICE_SERVICE_HOST: http://price-service
    PRICE_SERVICE_URL: http://price-service
    PRICE_SERVICE_PORT: 80
    PRICES_PATH: v1/prices
    ACCOUNT_SERVICE_HOST: http://account-service
    ACCOUNT_SERVICE_PORT: 80
    ACCOUNT_BALANCE: v1/balances
    ACCOUNT_ASSETS: v1/assets
    ACCOUNT_COVALENT_BALANCES: v1/balances/covalent
  blockscan:
    BLOCKSCAN_BNB_KEY: VEZ25IGVDIC7RHYR6S4PFNZQBSMITSX8PP
    BLOCKSCAN_ETH_KEY: UVBZ773WZQ8B6R53APKFFFN4MZ9EZR4F8G
    BLOCKSCAN_BNB_URL: https://api.bscscan.com/api
    BLOCKSCAN_ETH_URL: https://api.etherscan.io/api
    BLOCKSCAN_FTM_KEY: QSA6NJ6SGZG2MK13Q86MS3JYUB5PQQ1UGZ
    BLOCKSCAN_FTM_URL: https://api.ftmscan.com/api
    BLOCKSCAN_MOVR_KEY: EY5CDJTTRI349GAY4A382AC7G9WNH3Y1Y3
    BLOCKSCAN_MOVR_URL: https://api-moonriver.moonscan.io/api
    BLOCKSCAN_PLG_KEY: TXKCKK5YXGBWEH8YTGWNKCSJPGFKQ2IZZF
    BLOCKSCAN_PLG_URL: https://api.polygonscan.com/api
  params:
    JOBS_CACHE_TTL_IN_SECONDS: 86400
    AWS_XRAY_DAEMON_ADDRESS: xray-service.default:2000
  logs:
    LOG_AWS_ENABLED: true
    LOG_LEVEL: debug
    NODE_ENV: development

secrets:
  - database
  - redis
  - bscscan
  - etherscan
  - logs
  - sentry
