import Joi from 'joi';

export const dataSourceConfig = {
  // Third Part Subgraphs & Data Fetching API's
  AMM_UNISWAP_V3_ETH_SUBGRAPH_URL: Joi.string().required(),
  AMM_UNISWAP_V3_ARBI_SUBGRAPH_URL: Joi.string().required(),
  AMM_UNISWAP_V3_OPT_SUBGRAPH_URL: Joi.string().required(),
  AMM_UNISWAP_V3_PLG_SUBGRAPH_URL: Joi.string().required(),
  AAVE_ETH_SUBGRAPH_URL: Joi.string().required(),
  AAVE_PLG_SUBGRAPH_URL: Joi.string().required(),
  AAVE_AVAX_SUBGRAPH_URL: Joi.string().required(),
  AMM_UNISWAP_SUBGRAPH_URL: Joi.string().required(),
  AMM_PANGOLIN_SUBGRAPH_URL: Joi.string().required(),
  BLOCKS_SUBGRAPH_URL: Joi.string().required(),
  AMM_PANCAKE_SUBGRAPH_URL: Joi.string().required(),
  SPOOKYSWAP_FARM_SUBGRAPH_URL: Joi.string().required(),
  SPOOKYSWAP_ACELAB_SUBGRAPH_URL: Joi.string().required(),
  AUTOFARM_SUBGRAPH_URL: Joi.string().required(),
  QUICKSWAP_SUBGRAPH_URL: Joi.string().required(),
  SUSHISWAP_ARBI_EXCHANGE_SUBGRAPH_URL: Joi.string().required(),
  COMPOUND_ETH_SUBGRAPH_URL: Joi.string().required(),
  SUSHISWAP_AVAX_EXCHANGE_SUBGRAPH_URL: Joi.string().required(),
  SUSHISWAP_BSC_EXCHANGE_SUBGRAPH_URL: Joi.string().required(),
  SUSHISWAP_CELO_EXCHANGE_SUBGRAPH_URL: Joi.string().required(),
  SUSHISWAP_ETH_EXCHANGE_SUBGRAPH_URL: Joi.string().required(),
  SUSHISWAP_FTM_EXCHANGE_SUBGRAPH_URL: Joi.string().required(),
  SUSHISWAP_HECO_EXCHANGE_SUBGRAPH_URL: Joi.string().required(),
  SUSHISWAP_MATIC_EXCHANGE_SUBGRAPH_URL: Joi.string().required(),
  SUSHISWAP_MRIVER_EXCHANGE_SUBGRAPH_URL: Joi.string().required(),
  SUSHISWAP_OKEX_EXCHANGE_SUBGRAPH_URL: Joi.string().required(),
  SUSHISWAP_ONE_EXCHANGE_SUBGRAPH_URL: Joi.string().required(),
  SUSHISWAP_GNOSIS_EXCHANGE_SUBGRAPH_URL: Joi.string().required(),
  SUSHISWAP_ARBI_BENTOBOX_SUBGRAPH_URL: Joi.string().required(),
  SUSHISWAP_BSC_BENTOBOX_SUBGRAPH_URL: Joi.string().required(),
  SUSHISWAP_ETH_BENTOBOX_SUBGRAPH_URL: Joi.string().required(),
  SUSHISWAP_PLG_BENTOBOX_SUBGRAPH_URL: Joi.string().required(),
  SUSHISWAP_GNOSIS_BENTOBOX_SUBGRAPH_URL: Joi.string().required(),
  SUSHISWAP_ETH_MASTERCHEF_SUBGRAPH_URL: Joi.string().required(),
  SUSHISWAP_ETH_SUSHIBAR_SUBGRAPH_URL: Joi.string().required(),
  SUSHISWAP_ARBI_MINICHEF_SUBGRAPH_URL: Joi.string().required(),
  SUSHISWAP_CELO_MINICHEF_SUBGRAPH_URL: Joi.string().required(),
  SUSHISWAP_MRIVER_MINICHEF_SUBGRAPH_URL: Joi.string().required(),
  SUSHISWAP_ONE_MINICHEF_SUBGRAPH_URL: Joi.string().required(),
  SUSHISWAP_PLG_MINICHEF_SUBGRAPH_URL: Joi.string().required(),
  SUSHISWAP_GNOSIS_MINICHEF_SUBGRAPH_URL: Joi.string().required(),
  SUNDAESWAP_URL: Joi.string().required(),
  ALPACA_SUBGRAPH_URL: Joi.string().required(),
  ALPACA_API_URL: Joi.string().required(),
  AUTOFARM_API_URL: Joi.string().required(),
  PANCAKEV2_MAIN_STAKING_SUBGRAPH_URL: Joi.string().required(),
  YEARN_ETH_SUBGRAPH_URL: Joi.string().required(),
  YEARN_FTM_SUBGRAPH_URL: Joi.string().required(),
  YEARN_V1_ETH_SUBGRAPH_URL: Joi.string().required(),
  KAVA_API: Joi.string().required(),
};
