configMaps:
  nodes:
    ETH_URL: https://mainnet.infura.io/v3/d38bddd842b94305a23f91596991a9eb
    BSC_URL: https://bsc-dataseed.binance.org
    POLYGON_URL: https://polygon-mainnet.infura.io/v3/2f6833b1ce1649e0869b7250a6ea169b
    FTM_URL: https://rpc.ftm.tools/
    AVAX_URL: https://api.avax.network/ext/bc/C/rpc
    ARBITRUM_URL: https://arb1.arbitrum.io/rpc
  logs:
    LOG_AWS_ENABLED: true
    LOG_LEVEL: debug
    NODE_ENV: production

secrets:
  - database
  - redis
  - logs
