configMapsAWS:
  - opportunities

secrets:
  - database
  - redis
  - logs
  - sentry
  - multifarm

#configMaps:
#  common:
#    INTEGRATION_SERVICE_URL: http://integration
#  config:
#    HTTP_TIMEOUT: 60000
#    HTTP_MAX_REDIRECTS: 2
#  logs:
#    LOG_AWS_ENABLED: true
#    LOG_LEVEL: debug
#    NODE_ENV: development
#    AWS_XRAY_DAEMON_ADDRESS: xray-service.default:2000
