export enum FeatureEnum {
  pools = 'pools', // +
  staking = 'staking', // +
  farming = 'farming', // +
  claimable = 'claimable', // +
  lending = 'lending', // +
  collateral = 'collateral', // +
  borrowing = 'borrowing', // +
  transactions = 'transactions', // -
  leverageFarming = 'leverageFarming',
  health = 'health',
  lockedBalances = 'lockedBalances',
  bootstrap = 'bootstrap',
  shortFarm = 'shortFarm',
  mint = 'mint',
  // derivatives = 'derivatives',
  // exchange = 'exchange',
  // seigniorage = 'seigniorage',
  // assetManagement = 'assetManagement',
  // perpetualsExchange = 'perpetualsExchange',
  // options = 'options',
  // payroll = 'payroll',
  // fundManager = 'fundManager',
  // noLossLottery = 'noLossLottery',
  // realEstate = 'realEstate',
  // marginTrading = 'marginTrading',
  // assetBundles = 'assetBundles',
  // tokenizedRiskProtocol = 'tokenizedRiskProtocol',
}
