apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "defiyield-service.fullname" . }}-configs
  labels:
    {{- include "defiyield-service.labels" . | nindent 4 }}
data:
  {{- range $name, $keys := .Values.configMaps }}
  {{- range $key, $value := $keys }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}