apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: {{ include "defiyield-service.fullname" . }}
  labels:
    {{- include "defiyield-service.labels" . | nindent 4 }}
  annotations:
    strategy.spinnaker.io/max-version-history: {{ .Values.application.maxVersions | quote }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "defiyield-service.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "defiyield-service.labels" . | nindent 8 }}
    spec:
      initContainers:
      - name: secrets-compose
        image: stedolan/jq
        workingDir: /mnt
        command: ["sh", "-c"]
        args: ["jq -r 'to_entries|map(\"\\(.key)=\\(.value|tostring)\") | .[]' secrets-manager/* > secrets/.env"]
        volumeMounts:
        - name: secrets-manager
          mountPath: /mnt/secrets-manager
          readOnly: true
        - name: secrets
          mountPath: /mnt/secrets
      {{- if .Values.initContainer.enabled -}}
        {{- with .Values.initContainer }}
      - name: {{ .name }}
        {{- toYaml .spec | nindent 8 }}
        {{- end }}
        {{- if .Values.initContainer.image }}
        image: {{ .Values.initContainer.image }}
        {{ else }}
        image: {{ include "defiyield-service.image" . }}
        {{- end }}
        env:
          - name: ENV
            value: .env
        volumeMounts:
          - name: secrets
            mountPath: /usr/src/app/dist/apps/{{ include "defiyield-service.fullname" . | replace "-" "_" }}/.env
            subPath: .env
            readOnly: true
        envFrom:
          - configMapRef:
              name: {{ include "defiyield-service.fullname" . }}-configs
      {{- end }}
      containers:
      - name: application
        image: {{ include "defiyield-service.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: SERVICE_NAME
          value: "{{ .Values.application.name | replace "-" " " | title }}"
        - name: SERVICE_HOST
          value: {{ .Values.service.host | quote }}
        - name: SERVICE_PORT
          value: {{ .Values.service.port | quote }}
        - name: ENV
          value: .env
        - name: LOG_LEVEL
          value: {{ .Values.application.log_level | quote }}
        envFrom:
        {{- if .Values.configMaps }}
        - configMapRef:
            name: {{ include "defiyield-service.fullname" . }}-configs
        {{- end }}
        {{- if .Values.configMapsAWS }}
        {{- range $name := .Values.configMapsAWS }}
        - secretRef:
            name: {{ $.Values.application.name }}-{{ $.Values.application.environment }}-{{ $name }}
        {{- end }}
        {{- end }}
        ports:
        - name: http
          protocol: TCP
          containerPort: {{ .Values.service.port }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 10 }}
        livenessProbe:
          {{- toYaml (.Values.livenessProbe | default .Values.readinessProbe) | nindent 10 }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - name: secrets
          mountPath: /usr/src/app/dist/apps/{{ include "defiyield-service.fullname" . | replace "-" "_" }}/.env
          subPath: .env
          readOnly: true
      {{- with .Values.extraContainers }}
      {{ tpl . $ | nindent 6 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 10 }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "defiyield-service.fullname" . }}
      {{- end }}
      volumes:
      - name: secrets-manager
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: {{ include "defiyield-service.fullname" . }}-secrets
      - name: secrets
        emptyDir:
          medium: Memory
