{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "defiyield-service.fullname" . }}
  labels:
    {{- include "defiyield-service.labels" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.iam_role_arn }}-{{ .Values.application.environment }}
{{- end }}