apiVersion: v1
kind: Service
metadata:
  name: {{ include "defiyield-service.fullname" . }}
  labels:
    {{- include "defiyield-service.labels" . | nindent 4 }}
spec:
  selector:
    service: {{ include "defiyield-service.fullname" . }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http