ingress:
  enabled: true
  host: price.defiyield.app

configMaps:
  db:
    DB_SCHEMA: prices
  thegraph:
    THEGRAPH_UNISWAP_ENDPOINT: https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v2
    THEGRAPH_SUSHISWAP_ENDPOINT: https://api.thegraph.com/subgraphs/name/tretiakpk/sushiswap-fork-of-uniswap-v2
    THEGRAPH_CURVE_ENDPOINT: https://api.thegraph.com/subgraphs/name/tretiakpk/curve
    THEGRAPH_BALANCER_ENDPOINT: https://api.thegraph.com/subgraphs/name/dashvm7/balancer
    THEGRAPH_PANCAKE_ENDPOINT: https://api.thegraph.com/subgraphs/name/tretiakpk/cake
  links:
    SWAP_0X_ENDPOINT: https://api.0x.org/swap/v1/
    ETH_URL: https://mainnet.infura.io/v3/d38bddd842b94305a23f91596991a9eb
    BSC_URL: https://bsc-dataseed.binance.org
    CURRENCYLAYER_API_KEY: 82aa76fc01397164f25dc02a7acc652b
    CURRENCYLAYER_ENDPOINT: http://api.currencylayer.com/live
  logs:
    LOG_AWS_ENABLED: true
    NODE_ENV: production
    SENTRY_DSN: https://d3623ec62dd14dbe81d0b82391c95d5d@o1128743.ingest.sentry.io/6171835
  config:
    CACHE_HISTORIC_PRICES_TTL_IN_SECONDS: 172800
    BODY_LIMIT: 50mb
    URL_LIMIT: 50mb

secrets:
  - database
  - redis
  - bscscan
  - etherscan
  - logs
