ingress:
  enabled: true
  host: devscheduler.defiyield.app

configMaps:
  logs:
    LOG_AWS_ENABLED: true
    LOG_LEVEL: debug
    NODE_ENV: development

resources:
  requests:
    cpu: 100m
    memory: 200Mi
  limits:
    cpu: 100m
    memory: 200Mi

secrets:
  - database
  - redis
