# Danger js
# For more information see: https://danger.systems/js/
# https://github.com/marketplace/actions/danger-js-action

name: "Danger JS"
on: [pull_request]

jobs:
  build:
    name: Danger JS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - name: Danger

      - run: npm install

      - run: |
          DANGER_DISABLE_TRANSPILATION="true" DEBUG="*" npx danger ci
        name: "Running danger.js"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
