name: 'Prod Build'
on: [ pull_request ]

jobs:
  build:
    name: 'Run Prod Build'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout Git repository'
        uses: actions/checkout@v2

      - name: 'Set up Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          architecture: 'x64'
          check-latest: true
          cache: 'yarn'

      - name: 'Install Nest CLI'
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: global add @nestjs/cli

      - name: 'Install dependencies'
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: 'Run lint'
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: lint

      - name: 'Build project'
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build-monorepo
